name: Bug report
description: Create a bug report to help us improve Compass
title: "[Bug]: "
labels: [bug]
assignees:
  - zebozhuang
  - nilnon

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: your.email@example.com
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists of the bug.
      options:
      - label: I have searched all the existing issues
        required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Which the priority you think?
      options:
        - low (Default)
        - high
        - fatal
      default: 0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
      placeholder: |
        When I do <X>, <Y> happens and I see the error message attached below:
        ```...```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
      placeholder: When I do <X>, <Z> should happen instead.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Init environment ...
        2. Install Compass with version ...
        3. With those config ...
        4. Then run this '...'
        5. See error ...
      render: markdown
    validations:
      required: false

  - type: textarea
    attributes:
      label: Compass Log
      description: Detailed error log information is helpful for finding problems.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything else? (Additional Context)
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
    validations:
      required: false
