hadoop:
  namenodes:
    - nameservices: logs-hdfs
      namenodesAddr: [ "host1", "host2" ]
      namenodes: [ "namenode1", "namenode2" ]
      user: hdfs
      password:
      port: 8020
      matchPathKeys: [ "flume" ]

  yarn:
    - clusterName: "bigdata"
      resourceManager: [ "localhost:8088" ]
      jobHistoryServer: "localhost:19888"
