server:
  port: 7078

spring:
  application:
    name: task-gpt
  datasource:
#    url: jdbc:mysql://localhost:33066/compass?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://10.52.60.134:33066/diagnose_data?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: collation
    password: gcUHBQoCw6L15MY_x8OberqmRzSSGHxA-igEgwqmycg_Y6HyC3EIz7Qir4vAoKzi
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
  kafka:
#    bootstrap-servers: "localhost:9095"
    bootstrap-servers: "ht-diagnose-task-kafka.global.yyyvmc.kafka.oppo.local:9095,ht-diagnose-task-kafka.global.yyyqmc.kafka.oppo.local:9095,ht-diagnose-task-kafka.global.yyycmc.kafka.oppo.local:9095"
    consumer:
      topics: "log-exception"
      group-id: "cp-task-gpt"
      auto:
        start: true

  opensearch:
    nodes: localhost:9200
    username:
    password:
    truststore:
    truststore-password:
  jackson: # serialize & deserialize time zone.
    time-zone: Asia/Shanghai

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




